config/routes.rb
Rails.application.routes.draw do

  resource :settings, only: :show
  resource :welcome, only: :show

  root "welcome#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class ::Bot
  include Concurrent::Async

  def self.connection
    @@connection ||= self.new.async.connect
  end

  def self.token=(value)
    @@token = value
  end

  def self.application_id=(value)
    @@application_id = value
  end

  def connect
    bot = Discordrb::Bot.new token: Bot::Token, application_id: Bot::ID

    Rails.logger.info("Discord bot initialized")

    bot.message(with_text: 'Ping!') do |event|
      event.respond 'Pong!'
      Rails.logger.info("Discord bot: Pong!")
    end

    bot.run
  end
end

app/models/settings.rb
class Settings < ApplicationRecord
	include Settingson::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_if(section, action = nil)
    if match_controller(section, action)
      { class: 'active' }
    else
      { class: 'inactive' }
    end
  end

  def simple_form_horizontal(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(html: { class: "form-horizontal #{object}" }, wrapper: :horizontal_form)), &block)
  end

  protected
  def match_controller(section, action)
    (section == controller_path) and (action.nil? or action == action_name)
  end

  # def match_namespace(section)
  #   section == controller.class.parent.name.downcase
  # end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//discobot.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  - if message.is_a?(String)
    .alert.alert-dismissible{class: "alert-#{ type.to_sym == :notice ? 'info' : 'success' }" }
      %button.close{ data: { dismiss: "alert" } }
        %span{:'aria-hidden' => true} &times;
        %span.sr-only Close
      = message
  - elsif message.is_a?(ActiveModel::Errors)
    .alert.alert-dismissible.alert-danger
      %button.close{ data: { dismiss: "alert" } }
        %span{:'aria-hidden' => true} &times;
        %span.sr-only Close
      - message.full_messages.each do |msg|
        %p= msg

app/views/layouts/_navbar.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to content_for?(:title) ? yield(:title) : Rails.application.class.parent_name, root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        -# %li{ active_if('cms') }
        -#   = link_to t('menu.cms', default: 'CMS'),  cms_path
        -# %li{ active_if('saml') }
        -#   = link_to t('menu.saml', default: 'SAML'),  saml_info_path
        -# %li{ active_if('sudis/api', 'show') }
        -#   = link_to t('menu.api', default: 'API'),  sudis_api_path
      %ul.nav.navbar-nav.navbar-right
        %p.navbar-text
          Version: #{ ::VERSION }
        %li{ active_if('settings') }
          = link_to settings_path do
            %span.glyphicon.glyphicon-cog
            = t('menu.settings')

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    %title= content_for?(:title) ? yield(:title) : Rails.application.class.parent_name
    %meta{charset: 'utf-8'}
    %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %meta{content: 'width=device-width, initial-scale=1', :name => 'viewport'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag controller_path, media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      = render 'layouts/navbar'
    .container-fluid
      = yield :header
    .container-fluid
      .row
        .col-md-8.col-md-offset-2
          = render 'layouts/messages'
    .container-fluid
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag controller_path, 'data-turbolinks-track' => true

app/views/settings/show.html.haml
%h1 Settings#show
%p Find me in app/views/settings/show.html.haml

app/views/welcome/show.html.haml
= link_to Bot::AddLink, class: 'btn btn-primary', target: "_blank" do
  Add bot to Server

.todo
  %h2 TODO
  %ul
    %li Add some feature

= render('disqus')